service: sls-python-devkit

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.7
  endpointType: regional
  deploymentBucket: serverless.sls-python-devkit.deploys
  environment:
    DYNAMODB_TABLE_USERS: users-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_USERS}"

package:
  exclude:
     - '**'
     - '!lambdas/**'
     - '!lib/**'

functions:
  create:
    handler: lambdas/http/users/create.handler
    events:
      - http:
          path: users/{user_id}
          method: post
          cors: true

  list:
    handler: lambdas/http/users/list.handler
    events:
      - http:
          path: users
          method: get
          cors: true

  get:
    handler: lambdas/http/users/get.handler
    events:
      - http:
          path: users/{user_id}
          method: get
          cors: true

  update:
    handler: lambdas/http/users/update.handler
    events:
      - http:
          path: users/{user_id}
          method: put
          cors: true

  delete:
    handler: lambdas/http/users/delete.handler
    events:
      - http:
          path: users/{user_id}
          method: delete
          cors: true

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    zip: true
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
